### ISSUE TITLE
Site update returns exit code 1

### ISSUE THREAD

**Issue by tersor** [WordOps/WordOps#114]
Hello.

I ran into this when using Ansible for issuing certificate on an existing site. I am able to reproduce the issue directly on the server too, like this:

```
root ~ # echo $?
0
root ~ # wo site update domain.tld --le
Issuing SSL cert with acme.sh
Deploying SSL cert with acme.sh
Adding /var/www/domain.tld/conf/nginx/ssl.conf
Adding /etc/nginx/conf.d/force-ssl-domain.tld.conf
Added HTTPS Force Redirection for Site  http://domain.tld
Reload : nginx     [OK]
Congratulations! Successfully Configured SSl for Site  https://domain.tld
Your cert will expire within 89 days.
'wp'
root ~ # echo $?
1
```

My guess is that `'wp'` causes this, and I notice it gets outputted on my other servers as well when running the same command.

[System Information](https://gist.github.com/46a39e424f0283af0a11b30770cd63b9).

- [x] lsb_release -a
- [x] wo info
- [x] nginx -V
- [x] wo -v
- [x] wp cli info --allow-root

**Comment by VirtuBox** [comment]
Hello @tersor,
It will be pretty hard to give you an answer because you are using WordOps (wo) v3.9.5.3.
I have fully updated the letsencrypt stack with the release v3.9.6 and several additional fixes were added in the last releases (current version is v3.9.7.2). 
So, I can only recommend you to update WordOps to the latest release before running this test again.

**Comment by tersor** [comment]
Ok, I updated and ran the test again. No issues. Thank you!
