### ISSUE TITLE
Nginx sites-available files should have .conf

### ISSUE THREAD

**Issue by andremacola** [WordOps/WordOps#116]
All site configuration files created by WordOps should have .conf files in their names.
This is a standard format and helps when editing the file using editors with colored syntaxes.

**Comment by VirtuBox** [comment]
Hello @andremacola,
This is only related to editors configuration, because default Nginx configuration doesn't use .conf in sites-enabled and sites-available : 

```nginx
include /etc/nginx/sites-enabled/*;
```
.conf files are only the standard in other directory like `conf.d` : 

```nginx
include /etc/nginx/conf.d/*.conf;
```

If you use nano, the configuration available with the script [nanorc](https://github.com/scopatz/nanorc) automatically color Nginx syntaxes in sites-available and sites-enabled directories
