### ISSUE TITLE
WP Redis cache not connecting

### ISSUE THREAD

**Issue by majiix** [WordOps/WordOps#143]
Hi,
I transfered one of my wp sites to WordOps and updated it to --wpredis, but in redis settings in wp admin i see not connected message:

```
Status: | Not Connected
Client: PhpRedis (v5.0.2)
```

And when i try to open redis from backend `https://*.*.*.*:22222/cache/redis/phpRedisAdmin/` i get this error:

`ERROR: Connection refused [tcp://127.0.0.1:6379]`

Redis debug log:

```
Status: Not Connected
Client: PhpRedis (v5.0.2)
Drop-in: Valid
Connection Exception: Connection refused (RedisException)
Redis Extension: 5.0.2
Predis Client: 1.1.1
PHP Version: 7.3.9-1+ubuntu18.04.1+deb.sury.org+1
Multisite: No
Global Prefix: "gbz_"
Blog Prefix: "gbz_"
WP_CACHE_KEY_SALT: "***.com:"
Global Groups: [
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs"
]
Ignored Groups: [
    "counts",
    "plugins",
    "blog-details",
    "blog-id-cache",
    "blog-lookup",
    "global-posts",
    "networks",
    "rss",
    "sites",
    "site-details",
    "site-lookup",
    "site-options",
    "site-transient",
    "users",
    "useremail",
    "userlogins",
    "usermeta",
    "user_meta",
    "userslugs",
    "blog_meta",
    "wordfence",
    "wordfence-ls",
    "themes"
]
Dropins: 
 - Redis Object Cache Drop-In v1.4.3 by Till Krüss
Plugins:***
```

What's the solution for this?

**Comment by majiix** [comment]
And here is the `wp redis status` command result:

```
PHP Notice:  Undefined index: HTTP_X_FORWARDED_PROTO in phar:///usr/local/bin/wp                                                                                                                     /vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1198) : eval()'d code on line 1
RedisException: Connection refused in /var/www/***.com/htdocs/wp-content/obj                                                                                                                     ect-cache.php:447
Stack trace:
#0 /var/www/***.com/htdocs/wp-content/object-cache.php(447): Redis->connect(                                                                                                                     '127.0.0.1', 6379)
#1 /var/www/***.com/htdocs/wp-content/object-cache.php(185): WP_Object_Cache                                                                                                                     ->__construct(true)
#2 /var/www/***.com/htdocs/wp-includes/load.php(589): wp_cache_init()
#3 /var/www/***.com/htdocs/wp-settings.php(116): wp_start_object_cache()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1238): re                                                                                                                     quire('/var/www/perfik...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1159): WP                                                                                                                     _CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunn                                                                                                                     er.php(23): WP_CLI\Runner->start()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\B                                                                                                                     ootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#8 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\boot                                                                                                                     strap()
#9 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#10 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#11 {main}
Status: Not Connected
Client: PhpRedis (v5.0.2)
```

**Comment by VirtuBox** [comment]
Hello, issue has been fixed with PR https://github.com/WordOps/WordOps/pull/144.
A new release will be available in the next 15 minutes

**Comment by majiix** [comment]
Thank you. The issue is fixed and i should say that before 3.9.8.11 release WP was very slow either on the backend or frontend, now it's working much faster. Thanks

**Comment by ibrahimhajjaj** [comment]
Got the same issue @VirtuBox

**Comment by Torwald45** [comment]
I have two websites on the server. Both were transferred. On the first one, redis works well (it didn't use redis before it was moved). On the second one I have "Redis is unreachable: No such file or directory [unix:/run/redis/redis.sock] ". When moving the second one, I had to delete /wp-content/object-cache.php otherwise I had a fatal error. What to do?

**Comment by vikas5914** [comment]
@Torwald45 install Redis again and make sure it is running.

**Comment by Torwald45** [comment]
Redis is installed and working. The first website is doing well. For the second website, the command `wo site update my-address.com --wpredis ` returns can not update wp wpredis to wp wpredis.

I would try disabling and enabling something like wo site remove my-address.com --wpredis but there is no such command.

What about the file /wp-content/object-cache.php, does it have to be there? Because he's not there right now.

**Comment by vikas5914** [comment]
@Torwald45, you can upgrade to something else and return to wpredis. 

Also, I have found Wprocket to be better compared to Redis.. you can download it from gpldl.com

**Comment by Torwald45** [comment]
@vikas5914 "Redis is used to perform object caching. This is a different type of caching than the page caching provided by WP Rocket." (https://docs.wp-rocket.me/article/1359-redis-object-caching).

I managed to get Redis running on the second site. The /wp-content/object-cache.php file must be there and I had to change the settings in wp-config.php.

Now I have another problem. Redis doesn't want to work on both sites at the same time. It only works on one at a time. The second one returns to the standard theme. How to divide it so that the Redis server serves more pages?
