### ISSUE TITLE
Query String Caching is Not Caching

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#184]
First, AMAZING application you've built. It's lightweight and easy to use.

The issue I'm running into this.

When I setup caching, any caching plugin, but for this test, I'm using W3TC, it works beautifully.

I can hammer the server using ApacheBench and it doesn't even blink at 500 concurrent connections.

However, when I add a query string parameter to the page, even with the options enabled in W3TC,  or any caching plugin, it doesn't cache the page properly and my server CPU spikes.

For example..

domain.com/this-page/

caches GREAT. Even with the required dynamic PHP in the backend, no problem. I am using Ad Inserter and its Ad Rotation feature to rotate ads, and it runs without issue.

But as soon as I do this

domain.com/this-page/?param=value

My server starts to tank at the same levels.

No query string, 0.05 load
With query string, jumps up to 30.0 or 40.0 load

This makes me believe it's not specific to hardware, but more likely something software in the nginx or similar configuration.

Any advice or solutions? TIA

**Comment by dingman** [comment]
System info:  sudo wo info

NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1

PHP (7.2.23-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

MySQL (10.3.18-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             98
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

**Comment by VirtuBox** [comment]
Hello @dingman,
That's great to know you enjoy WordOps.

About query string caching, it's the normal behavior to bypass cache on query strings because with url rewriting enabled, only the page we should not serve from cache use query string in their urls. 

I haven't used W3TC enough to know if there is an option to force page cache even for urls with a query string, but it's possible to enable it with the other caching system supported by WordOps.
It will be even faster than with W3TC, not because another plugin is better, but only because our Nginx configurations provide the ability to serve pages from cache directly with Nginx (without making a single request to WordPress). This way the server load do not increase, and pages are served instantly. 

And you will be able to allow query string caching by editing our mapping exclusion configuration in `/etc/nginx/conf.d/map-wp-fastcgi-cache.conf`.

**Comment by dingman** [comment]
I found a solution, I'll be doing a blog post write-up on it soon and I'll reply back with it.
