### ISSUE TITLE
Delete x-powered-by WordOps

### ISSUE THREAD

**Issue by swissky** [WordOps/WordOps#196]
Hi, please delete the x-powered header, its a security risk.

thx

**Comment by VirtuBox** [comment]
Hello @swissky,

We already removed WordOps release number from the header `X-Powered-By`, so I do not see how this header could be a security risk anymore ?

**Comment by sheatsb** [comment]
@swissky  Agreed, because if there's any vulnerability - since we can't trust that the latest version is being used - it's a risk to expose what's powering the setup.

I've been able to remove this manually by using
`server_tokens off;`
`more_clear_headers 'x-powered-*';`
in a custom nginx config.

**Comment by VirtuBox** [comment]
@sheatsb the probability of vulnerability in WordOps is very low because it's only a command-line tool which configure third-party applications. If you remove WordOps from your server, your sites will be still running well. 
If I tell you wordops.net is running with WordOps, it only let you know it's running with Nginx, PHP-FPM and MariaDB, like the most part of other WordPress sites.

**Comment by jatin23pasrija** [comment]
Just comment the line in /etc/nginx/nginx.conf file and reload the nginx service. "#more_set_headers "X-Powered-By : WordOps";"
