### ISSUE TITLE
https://wordops.org is down

### ISSUE THREAD

**Issue by demyxco** [WordOps/WordOps#23]
Couldn't find a contact email so I posted here.

**Comment by buzucan** [comment]
i think that was WordOps. :)

**Comment by yogoeasy** [comment]
Same here. Error message: DNS_PROBE_FINISHED_NXDOMAIN

**Comment by brianjking** [comment]
Yea, looks like domain may have expired. Not a good sign. http://whois.domaintools.com/wordops.org

**Comment by w33zy** [comment]
This really is not a good sign. Especially since there are a couple open tickets that can be closed with a 1 line patch, that have been open for a while.

**Comment by nsgoyat** [comment]
@VirtuBox  What you think about this master? Has this project been abandoned already? These guys couldn't deliver even a single stable version. I totally respect the developers and it's also quite hard to remain committed to such type of free project but a lot of guys had some big hopes up for this project :(

**Comment by VirtuBox** [comment]
Hello, 

I haven't noticed immediately the domain was unavailable because I have previously overwritten my DNS locally. I sent a message to @jeroenops & @michelkusters to ask them if the issue will be fixed soon.

About WordOps project, I haven't found enough free time during the past few weeks to work on the install script and to fix the current issues. It should be better now, since i have released nginx-ee v3.5.1. 

But I will talk with WO developers and we will try to set the next release deadline (and to announce it), to provide at least a working version of EEv3 in the new few weeks. This way, if the stable release isn't published before the deadline, you will be free to start looking for another solution.

**Comment by nsgoyat** [comment]
Hello Master,
Thanks for the quick and positive response. It's great to see you backing up this project. It was just my two cents. I have been following your guides & work for more than a year and I am not going to look for another solution. I will just follow your updates :)

**Comment by michelkusters** [comment]
Hi guys,

Just to let you know; we are well aware about the troubles with our domain name(s). We agree that this is highly unprofessional. Due to a misunderstanding with the registrar, the domain was expired and the controlling account deactivated. However, we are doing everything in our power to regain control and expect it to be back as soon as possible.

On a more positive note: this is also the reason why we held back on our 3.9.5 release, since there are ties in the code with our domain. Once it’s back we’ll publish this new and deemed stable release in no-time. To give you a heads-up, some changes in the 3.9.5 release:

• Fixed the installer for both clean installations and migrations
• Migrated to OpenResty, in favor of proper Debian support
• We’ve ditched Postfix in the previous release, it’s replaced by OpenSMTPd with 3.9.5 - so expect nice notifications and updates from your server

Best regards,

Jeroen and Michel

@VirtuBox A big thank you for jumping in as well!

**Comment by buzucan** [comment]
Hi michel but you can't pull this version to github? Last pull date is on december... :(

**Comment by handpressed** [comment]
What's the timeline on this? I'd like to give WordOps a try after recently switching may main WP server to EE4, which is proving to be somewhat problematic.

**Comment by h3artbl33d** [comment]
The installer already has _most issues_ fixed, though we are working to fix LE as well - independent of the domain troubles.

That said, we are putting all effort in - and more - to regaining complete control over the domain.

**Comment by jeroenops** [comment]
The installer already has _most issues_ fixed, though we are working to fix LE as well - independent of the domain troubles.

That said, we are putting all effort in - and more - to regaining complete control over the domain.

**Comment by ingobaab** [comment]
Hello,

 I had a short chat on facebook with @VirtuBox (Thomas) and after that I want to "offer" a domain you maybe could use as an alternative for this project - if you want. I do not know how you "are in love" with the name 'wordops', but if you have difficulties to get it back to life here is my offer:

 I did myself some work "forking" ee to a new script, but I do not have enough time to maintain it constantly and hold the quality high. So my domain I wanted to use for this lays fallow: "sharedengine.io". 
Please think about it and contact me, if you want to change the name of your  project - I can and would also offer a free VPS for hosting the website...  @michelkusters and @jeroenops please contact  me directly if you are interessted..

**Comment by buzucan** [comment]
maybe another extension .com, .info?

**Comment by vikas5914** [comment]
maybe just github.io page?

**Comment by VirtuBox** [comment]
Community forum is back online on https://community.wordops.io/
