### ISSUE TITLE
Regular resetting permissions

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#248]
Since I often login as sudo su - to perform actions, many files/directories end up as root:root ownership.

Should there be a cron running that regularly resets file/directory permissions to the correct www-data to ensure no permission issues?

**Comment by StinkyBytes** [comment]
i have been using this solution for a few years already.  works perfect.
https://sammaye.wordpress.com/2018/08/09/use-bindfs-for-serving-ssh-users-with-web-server-access/

**Comment by VirtuBox** [comment]
> i have been using this solution for a few years already. works perfect.
> https://sammaye.wordpress.com/2018/08/09/use-bindfs-for-serving-ssh-users-with-web-server-access/

Nice and useful tutorial @StinkyBytes. It's look like a good solution to avoid permissions issues. I will try to find more information about this to check if I can implement this in WordOps. 

@dingman adding a command to fix wordpress files and directories permissions is already planned. But it highly depends on php-fpm pool per site integration task, because each site will use a different user to provide a proper isolation between sites.

**Comment by dingman** [comment]
Great! Looking forward to seeing it. Thanks @StinkyBytes @VirtuBox
