### ISSUE TITLE
--proxy sites not including /conf/nginx/* so site SSL do not work

### ISSUE THREAD

**Issue by rslonik** [WordOps/WordOps#288]
Hi,

When creating a new proxy site (`wo site create site.com --proxy=127.0.0.1=3000`) the host config doesn't include `include {{webroot}}/conf/nginx/*.conf;` from template.

So when you install HTTPS on that site (`wo site update site.com --le`) the `/conf/nginx/ssl.conf` is not used and the SSL won't work.

I tried changing last two lines of `/usr/lib/wo/templates/virtualconf.mustache` from:
```
include common/locations-wo.conf;{{/proxy}}
include {{webroot}}/conf/nginx/*.conf;
```
to:
```
include common/locations-wo.conf;
include {{webroot}}/conf/nginx/*.conf;{{/proxy}}
```

But it didn't work. I certified that this is the file being used by putting some random comment and creating again the site. 

Can someone help fixing this template?

**Comment by janiosarmento** [comment]
May I suggest a workaround?

Create a copy of the default `virtualconf.mustache` into `/root/.wo/templates` (you'll have to create it).

Then, edit this file and just before the line `{{/proxy}}` (line 39, I guess) add the directive you want the proxy vhosts to have:

`include {{webroot}}/conf/nginx/*.conf;`

Now, when you create your new vhosts WO will use your custom template instead of the default one.
