### ISSUE TITLE
LetsEncrypt SSL Renwal issue when multiple domain from different CloudFlare accounts

### ISSUE THREAD

**Issue by msdev20** [WordOps/WordOps#302]
SSL renewal issue when two domains from different Cloudflare account, because of acme.sh config store last Cloudflare account credential.

Can you add domain wise config-home for acme.sh like Nginx custom config in /var/www/config/nginx.

acme.sh support custom config-home
https://github.com/acmesh-official/acme.sh/issues/1278#issuecomment-366410085 

System Information

- [x] `lsb_release -a`
- [x] `wo info`
- [x] `nginx -V`
- [x] `wo -v`
- [x] `wp cli info --allow-root`

[wo_system_info.txt](https://github.com/WordOps/WordOps/files/4896362/wo_system_info.txt)

**Comment by VirtuBox** [comment]
Hello @msdev20, 
because it's a very specific issue which add a layer of complexity in certificates management without being required for the most part of users, I'm not sure to have enough time to work on a workaround for this issue. 
To handle this, you can also create an empty cloudflare account and invite it as member of your other accounts. This way, you will be able to use the same API credential for all domains on multiple accounts.

**Comment by renatofrota** [comment]
I can see WordOps already pass `--config-home` parameter to acme.sh (currently set to `/etc/letsencrypt/config`) when issuing certs. The only change would be to set it a per-domain location like `/var/www/domain.tld/conf/acme.sh/config` and set a new cron entry per-site (passing the same config-home) or am I missing anything else?
