### ISSUE TITLE
GIT Credentials

### ISSUE THREAD

**Issue by roshanjonah** [WordOps/WordOps#305]
I see that www-data user runs the show but we have a lot of GIT repos and we use HTTP not SSH so what is the best way to store the GIT credentials. Every time I store .gitconfig file, it just won't give permission for www-data to read that. I tried CHMOD and chown but nothing seems to work. It would keep saying

`error: could not lock config file /var/www/.gitconfig: Permission denied`

I even tried making a home directory for a www-data user and adding .gitconfig there but wouldn't work there either. I am sure you guys use GIT Repos too - how did you guys do it? It's a hassle to do it as root and then to run chown to make sure all files belong to www-data after minor changes straight to the server.

**Comment by VirtuBox** [comment]
Hello @roshanjonah,
www-data user cannot write anything in /var/www because this directory's owner is root.
So you can create the .gitconfig file as root, and then change owner and permissions with `chown www-data:www-data /var/www/.gitconfig && chmod 644 /var/www/.gitconfig`.
Or you can change /var/www directory owner (`chown www-data /var/www`) to allow www-data to create files in this directory. 
But I lack for information about the possible security  issues resulting of  /var/www directory owner modification.

**Comment by tersor** [comment]
@VirtuBox, so nice to see you here again! :) 

@roshanjonah, we use git in our WordOps projects by changing the ownership in `/var/www/domain.tld/htdocs`. For example, create a deploy user and authenticate with ssh keys to your github account. Then you can do something like this:

```
FOLDER=/var/www/domain.tld/htdocs
chown -R deploy:www-data $FOLDER
find $FOLDER -type d -exec chmod 2755 {} +
find $FOLDER -type f -exec chmod 0644 {} +
```

You may want to exclude some folders by adding them to `.gitignore` and changing permissions back to `www-data`:

```
chown -R www-data:www-data "${FOLDER}/wp-content/uploads"
chown -R www-data:www-data "${FOLDER}/wp-content/cache"
```

Please note that file updates via the control panel does not work using the method above (since `www-data` has lost write permissions). But this is something you want to avoid anyway, when using git.

PS, if you want to use the root user when running git commands, you can add a reference to the deploy private key in `/root/.ssh/config`:

```
host github.com
  HostName github.com
  IdentityFile /home/deploy/id_rsa
```

You may want to fix file permissions again if the root user creates new files when fetching the repo.

**Comment by roshanjonah** [comment]
@VirtuBox Thank you! I tried that actually but when I imitate as www-data user `sudo su -s /bin/bash www-data` and then go into the GIT folder and do "git pull", it wouldn't be able to read the git config despite having it under www-data user and group and 644 file permission. I logged into www-data user and then tried creating .gitconfig file but even then, it can't read the file it just created under its home directory or /var/www/.gitconfig - No idea why! I also tried changing the www folder to be owned by www-data user - wouldn't work either! It's there but when I do git clone or git pull - it just wouldn't read. The .gitconfig looks something like this...
