### ISSUE TITLE
Feature Request: Do you want to upgrade?

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#331]
In the past year that I've been using WordOps, I noticed one thing which I think would make it a better experience.

The choice to upgrade and from what to what.

For example, when I run: "sudo wo update" it doesn't first tell me there is an update available, nor ask me if I want to continue.

I would love to see something like this.

Bash:

wo update

Current Version: X.XX.X
New Version Available: Y.YY.Y
Changelog: example.com/changelog/y.yy.y

Do you want to continue? y/N (default to N)

But not just for "wo update" -- the same for "wo stage upgrade"

Right now, I have no idea if there are any upgrades available for my stack. Nor do I know what the current version is and then going to if I run it. I'm pretty much blind in the upgrade process.

Having the version information and what changed between versions, would be really nice for system admins running WordOps.

**Comment by VirtuBox** [comment]
Hello @dingman, 
this is an excellent suggestion. 
For `wo update`, it will be pretty easy to add additional informations and to prompt user for confirmation. 
For `wo stack upgrade`, it's a little bit harder because we cannot simply compare template files with current stack .conf files before deploying them because templates variables are defined during conf deployment.

**Comment by dingman** [comment]
@VirtuBox here's a thought then.

for `wo stack upgrade` it only prompts when upgrading versions. In terms of conf files, have an option like you would for say a GRUB list, "keep current," "use maintainers," "update clean" etc. so that you don't have to worry about deciding for the user, but allow them the options.
