### ISSUE TITLE
config option for running nginx on non-default port 

### ISSUE THREAD

**Issue by bumblebeebh** [WordOps/WordOps#341]
I wish to run nginx on non-default port of 8080. There is no global config option to accomplish this.

Use case: run wordpress behind another reverse proxy web server. 

There is a mustache template here.. Should we modify this or can this be considered as a feature request?

https://github.com/WordOps/WordOps/blob/fdefecbfba5d28b7edea8c6212e6188e513533a8/wo/cli/templates/virtualconf.mustache

**Comment by VirtuBox** [comment]
Hello @bumblebeebh, 
to run Nginx on a non-default port, you  can edit the default vhost `/etc/nginx/sites-available/default`.
And replace : 
```nginx
        listen 80 default_server;
        listen [::]:80 default_server;
```
with : 
```nginx
        listen 8080 default_server;
        listen [::]:8080 default_server;
```
Then to run your vhost on the same port, you can create an additional file ports.conf in /var/www/yourdomain.tld/conf/nginx with the directives : 
```nginx
listen 8080;
listen [::]:8080;
```

Otherwise, yes you can use your own mustache template, by downloading and editing virtualconf.mustache and by putting it in /var/lib/wo/templates/ or /root/.wo/templates/. This way, it will override WordOps template.
