### ISSUE TITLE
migration from ee to wo: seems to lost all sites

### ISSUE THREAD

**Issue by romapad** [WordOps/WordOps#4]
No error during migration. But all my sites get down. 
Command sudo ee site info WEBSITE showing:
site WEBSITE does not exist
Command sudo ee stack reload showing:
'Namespace' object has no attribute 'php7'

Need help!

**Comment by romapad** [comment]
I had debian jessie installed

**Comment by manacim** [comment]
Have this issue too.

**Comment by jeroenops** [comment]
Thank you kindly for opening this issue. We were having some issues with this, they should be resolved. Could you update to the latest version? `wget -qO wo wordops.se/tup && sudo bash wo` should suffice.

**Comment by manacim** [comment]
@jeroenops same thing "site.com does not exist"

**Comment by manacim** [comment]
@jeroenops thanks for the patch, will this be included in the next update?

**Comment by jeroenops** [comment]
Yes! We'll communicate this broadly whenever it's ready. With the upcoming 3.9.5 release:
- This patch will be included
- We'll have a version of `nginx-custom` that supports Stretch (Debian Stretch support is broken ATM due to a dependency failure)
- We'll migrate Postfix to OpenSMTPd for outgoing mails/notifications

And perhaps more love and awesomeness :D

**Comment by manacim** [comment]
> Debian Stretch support is broken ATM due to a dependency failure

Oh damn I was just thinking of doing a fresh install of Debian 9 too.

**Comment by manacim** [comment]
Oh btw, I just migrate my other server (Ubuntu 18.04) to WordOps and it detects the sites from EEv3. Was this installer merged recently?

**Comment by jeroenops** [comment]
Yeah :) We are _on fire_ :)

**Comment by manacim** [comment]
Awesome, keep up the great work guys!

**Comment by cristianmenghi** [comment]
Need to adjust because use default config and dosent fit 
/etc/php/7.2/fpm/pool.d/www.conf

[www]
user = www-data
group = www-data
listen = 127.0.0.1:9072
listen.owner = www-data
listen.group = www-data
pm = ondemand
pm.max_children = 100
pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 30
ping.path = /ping
pm.status_path = /status
pm.max_requests = 500
request_terminate_timeout = 300

> Okay, I'll resolve this in the installer. A quick fix:
> 
> ```
> # Copy the EEv3 database to WordOps
> cp /var/lib/ee/ee.db /var/lib/wo/dbase-ee.db
> # Update the PHP versions in the database to 7.2
> echo "UPDATE sites SET php_version = REPLACE(php_version, '5.6', '7.2');" | sqlite3 /var/lib/wo/dbase.db
> echo "UPDATE sites SET php_version = REPLACE(php_version, '7.0', '7.2');" | sqlite3 /var/lib/wo/dbase.db
> # Replace the ports for PHP 7.2
> sed -i 's/9000/9072/g' /etc/nginx/conf.d/upstream.conf &>> /dev/null
> sed -i 's/9070/9072/g' /etc/nginx/conf.d/upstream.conf &>> /dev/null
> # Replace the ports for debug PHP 7.2
> sed -i 's/9001/9172/g' /etc/nginx/conf.d/upstream.conf &>> /dev/null
> sed -i 's/9170/9172/g' /etc/nginx/conf.d/upstream.conf &>> /dev/null
> ```

and need to adjust
/etc/php/7.2/fpm/pool.d/www.conf

[www]
user = www-data
group = www-data
listen = 127.0.0.1:9072
listen.owner = www-data
listen.group = www-data
pm = ondemand
pm.max_children = 100
pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 30
ping.path = /ping
pm.status_path = /status
pm.max_requests = 500
request_terminate_timeout = 300

**Comment by jeroenops** [comment]
> Is need to overwrite dbase-ee.db to dbase.db ?

No, when migrating you'll need to copy the EE database to the primary WO database; 

`cp /var/lib/ee/ee.db /var/lib/wo/dbase.db`

The `/var/lib/wo/dbase-ee.db` file merely serves as a backup ;)

**Comment by VirtuBox** [comment]
Issue has been fixed, WO install script now migrate properly site from EasyEngine v3
