### ISSUE TITLE
Make WO open ports on UFW during setup

### ISSUE THREAD

**Issue by gitouttaherenow** [WordOps/WordOps#481]
New to WordOps and my knowledge with linux is limited. Faced issues highlighted on this thread: https://community.wordops.net/d/1696-need-helpserver-is-unreachable

The problem is unaware users have no way of knowing why their sites aren't working. Mine was due to closed ports for http, https and others. After wasting 2 hours and brute forcing different solutions, I finally got my sites to work after open the ports on UFW. I assumed WO would take care of this for me, but apparently not.

My suggestion is to have the ports configured during WO setup.

**Comment by VirtuBox** [comment]
Hello @gitouttaherenow,
UFW was automatically configured by WordOps install script previously, but too many advanced users asked for making this configuration optional because Firewall rules are not something universal. So I have moved the configuration in the command `wo stack install --ufw`. But even this command will not make any change if UFW is already enabled (to avoid overwriting the previous configuration. I will add information about this issue in our documentation.

**Comment by gitouttaherenow** [comment]
Makes sense. A note on this issue in the guides or documentation would be good for beginners like me.
