### ISSUE TITLE
wo update is not updating configuration files

### ISSUE THREAD

**Issue by yogeshbeniwal** [WordOps/WordOps#555]
WordOps update to v3.17.0 from earlier v3.16.3 is not updating configuration files. This may be long ongoing un-noticed issue from older versions.

Example 1: Changes from https://github.com/WordOps/WordOps/pull/376 are not updated

![Screenshot](https://github.com/WordOps/WordOps/assets/7325107/0e85ee79-05ea-4e21-ba38-61340e4e5c48)

**Comment by VirtuBox** [comment]
Hello @yogeshbeniwal, you have to run `wo stack upgrade --nginx` to update nginx configuration files.

**Comment by yogeshbeniwal** [comment]
`wo stack upgrade --nginx` worked for that, however `wo stack upgrade` doesn't update wo.conf file modified in version v3.18.0.

Can `wo update` command be modified to handle these update automatically.

**Comment by VirtuBox** [comment]
Hello @yogeshbeniwal,

IMHO I prefer to not update all configurations files with `wo update`. The most important is to keep WordOps up-to-date on all servers, that mean making sure updating WordOps will not have any impact on users sites. Then you will be able to update the stack you want with `wo stack upgrade --<stack_name>`.
And it's not easy to update the file `wo.conf` because you can have custom configuration inside and/or want to keep the php version previously defined and not the latest one.
