### ISSUE TITLE
random user suggestion for site

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#63]
a small suggestion when creating the user for wordpress website.
wo site create manager.com --wp
wordpress user: manager_AXnbkS9iJfql
the user would follow the domain with a sequence of 12 characters or more.

thx.

**Comment by VirtuBox** [comment]
Hello,
WordOps, like EasyEngine, already provide the ability to define WordPress username, so I'm not sure generating random WordPress username is needed.

**Comment by juanpvh** [comment]
Yes, you're right.
my thinking is in just not having an equal login for everyone, having a different one, I believe this will increase security.

**Comment by VirtuBox** [comment]
It doesn't, because username is still displayed in WordPress RSS feed and it's pretty easy to get it using the wp-json API. We are working on a solution for this : 

exemple : http://yoursite.tld/wp-json/wp/v2/users/1

**Comment by demyxco** [comment]
Maybe you guys could use gpw? For my docker stack script that I wrote does this automatically via:

[/etc/functions/env.sh](https://github.com/demyxco/demyx/blob/master/etc/functions/env.sh)
```
docker run -it --rm demyx/utilities sh -c "gpw 1 10"
```

> WordOps, like EasyEngine, already provide the ability to define WordPress username, so I'm not sure generating random WordPress username is needed.

I kinda agree with you on this one but I just wanted to make life easier by not going through the install process. If it can be automated, why not?

**Comment by VirtuBox** [comment]
Hello, I'm not sure to understand the purpose of your script. Can you explain more about it?

**Comment by demyxco** [comment]
@VirtuBox my script uses Docker so it wouldn't work with WO but the package `gpw` is available in the repos for Ubuntu and _probably_ Debian.

**Comment by VirtuBox** [comment]
@demyxco ah ok I understand. Don't worry for that part, it can be done in python without having to use an additional package.
But like I said previously, I do not think random username is a way to secure WordPress properly because it's pretty easy to get a list of users by browsing RSS feed or wp-json API.
EasyEngine already included a rate limiter on /wp-login.php, and I'm working on fail2ban integration to add an additional layer on security on this page. I have also increased WordPress passwords size to 24 characters.
