### ISSUE TITLE
Create self-signed SSL site

### ISSUE THREAD

**Issue by tdtgit** [WordOps/WordOps#70]
Hi, ask I talked before on Slack. Would we support self-signed SSL site for internal uses? Maybe behind a proxy (in my case). Ask you first the I can working for a PR. Let's hope :)

So:
- 
* Would we use --self-signed-ssl (too long) or --sss (too meanless) when use `site create` and `site update`?
* How we create self-signed cert and key for server? Should we use `apt-get install ssl-cert` or generate by `openssl` command?
* What should I aware when implement this feature?

**Comment by VirtuBox** [comment]
Hello,

we are going to rewrite the letsencryt stack for scratch for the next WordOps release (v4.0), because there are too many limitations by keeping this stack in the command `wo site`  (the plugin [site.py](https://github.com/WordOps/WordOps/blob/master/wo/cli/plugins/site.py) is already too long with almost 2000 lines) and we would like to add acme challenge via DNS API as well as wildcard ssl certificate support.
So it should not be a problem to add other features like self-signed SSL certificate support but I do not recommend you to start working on the current stack, because if we keep this structure, it would be to difficult to implement other features later. 

So I was thinking about create the plugin `wo ssl` with commands like : 
```bash
wo ssl site.tld --letsencrypt

wo ssl site.tld --wildcard --dns_cf

wo ssl site.tld  --self-signed
```

Otherwise, you can find the function used to generate the self-signed certificate used to secure 22222 backend with openssl here : https://github.com/WordOps/WordOps/blob/0fd6a4cb59ec85736de919bdc57344c38bc3d608/wo/cli/plugins/stack.py#L470

**Comment by dingman** [comment]
+1 would be great to see this happen!

**Comment by dingman** [comment]
@VirtuBox how would I go about using that WOShellExec function to create a self-signed SSL cert with the current release?

**Comment by tdtgit** [comment]
Working on this feature :)
