### ISSUE TITLE
Staging and Development Setup

### ISSUE THREAD

**Issue by webonspeed** [WordOps/WordOps#99]
It would be great if we could implement a system where we could create a staging site and a live site then we could just migrate these across with a command in terminal.

For example staging.domain and domain.  I hate working on live servers and always work on staging sites to make sure everything is working fine before pushing to live server.  

Would it be possible to implement something like

wo site migrate staging.domain -> domain  

Or something similar?  If this was implemented then I think Wordops would be the best thing ever lol not that it is not so great at the moment ;) 

Kind Regards

Chris

**Comment by dingman** [comment]
A thought for implementation.

We have a customized implementation of WordOps that is highly available, using Redis+RDS (Aurora).

It would be great if there were options when deploying a site. Such as --themeonly --dbonly and default to --all

that way I could push just template changes (which will be typical), or even better, if I could push JUST Pages (not Posts)

Since our editorial team will continue publishing Posts, but rarely ever the Pages. That way I could modify a Page in staging, then deploy that Page or all Pages, and not touch the Posts.

Some food for thought and feedback.

Thanks for creating such an amazing platform, it's been fantastic to use and glad to see you're continuing to build on it.

**Comment by dingman** [comment]
Adding some more information from my experiences with well known managed hosting providers:

Some hosting companies offer the dev<>stage<>prod copying functionality, but it doesn't truly accommodate for when the design of the page is built within a page builder like Elementor.

As a possible follow-up phase, to allow for specific Pages or Post Types (such as Cloud Templates) to be pushed from one environment to another.

This would allow content to live in production; whereas if doing a full DB push from Staging>Prod, it would overwrite production blog posts and content that was available to the public. In turn, this would reduce headaches of missing content from production when moving between environments.

**Comment by techieshark** [comment]
Maybe see also https://deployer.org/
